services:
  - type: web
    name: ai-pest-detection-backend
    env: python
    branch: main
    rootDir: backend
    plan: free
    buildCommand: ""
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
